# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2021-02-23 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': '作者'},
        ),
        migrations.AlterModelTable(
            name='author',
            table='author',
        ),
    ]
